libraries:
  Filme:
    metadata_path:
      - metadata/movies/metadata.yml
      - metadata/movies/overlays.yml
      - metadata/movies/anime.yml
      - metadata/movies/serien.yml
      - metadata/movies/Filme.yml
      - metadata/movies/People.yml
      - metadata/movies/Genres.yml
      - metadata/movies/Awards.yml
      - metadata/movies/Decades.yml
      - metadata/movies/Watchlists.yml
    settings:
      asset_directory:
        - assets/movies/collections
        - assets/movies/filme
        - assets/movies/people
        - assets/movies/genres
        - assets/movies/awards
        - assets/movies/decades
        - assets/movies/watchlists
    operations:
      split_duplicates: true
  Anime:
    metadata_path:
      - metadata/anime/metadata.yml
      - metadata/anime/filme.yml
      - metadata/anime/Anime.yml
    settings:
      asset_directory:
        - assets/anime/collections
        - assets/anime/anime
  Serien:
    metadata_path:
      - metadata/tv_shows/metadata.yml
      - metadata/tv_shows/overlays.yml
      - metadata/tv_shows/filme.yml
      - metadata/tv_shows/Serien.yml
    settings:
      asset_directory:
        - assets/tv_shows/collections
        - assets/tv_shows/serien
  Movies:
    plex:
      url: <url>
      token: <token>
    split_duplicates: true
    metadata_path:
      - metadata/movies/metadata.yml
      - metadata/movies/overlays4k.yml
      - metadata/movies/Movies.yml
      - metadata/movies/People.yml
      - metadata/movies/Genres.yml
      - metadata/movies/Awards.yml
      - metadata/movies/Decades.yml
    settings:
      asset_directory:
        - assets/movies/collections
        - assets/movies/filme
        - assets/movies/people
        - assets/movies/genres
        - assets/movies/awards
        - assets/movies/decades
  Shows:
    plex:
      url: <url>
      token: <token>
    metadata_path:
      - metadata/tv_shows/metadata.yml
      - metadata/tv_shows/overlays.yml
      # - metadata/tv_shows/Shows.yml
    settings:
      asset_directory:
        - assets/tv_shows/collections
        - assets/tv_shows/serien
settings:
  tvdb_language: default
  cache: true
  cache_expiration: 60
  run_again_delay: 2
  sync_mode: sync
  show_unmanaged: true
  show_filtered: false
  show_missing: true
  save_missing: false
  missing_only_released: false
  asset_directory: assets
  asset_folders: true
  create_asset_folders: false
  assets_for_all: true
  show_missing_assets: true
  collection_minimum: 1
  delete_below_minimum: false
plex:
  url: <url>
  token: <token>
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
tmdb:
  apikey: <apikey>
  language: de
